package views;

import controllers.APIController;
import controllers.DbOperations;
import entities.Country;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.MappingDataDb;

/**
 *
 * @author Pantelis Ioannidis
 * @author Aris Dimakakos
 */

// R4 Προβολή δεδομένων Covid19 σε χάρτη
public class FrameMapSelection extends javax.swing.JFrame {

    /**
     * Creates new form FrameMapSelection
     */
    DbOperations db;
    APIController api;
    
    public FrameMapSelection() {
        initComponents();
        setIconImage();
        //Φτιάχνουμε το αντικείμενο που μεσολαβεί για την επικοινωνία με την βάση
        db = new DbOperations();
        //Φτιάχνουμε το αντικείμενο που μεσολαβεί για την επικοινωνία με τo API
        api = new APIController();
        //γεμίζουμε το combo και την λίστα με τα ονόματα των χωρών
        populateCountryComboBoxAndList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCountrySelection = new javax.swing.JLabel();
        jComboBoxCountry = new javax.swing.JComboBox<>();
        jLabelRestOfCountries = new javax.swing.JLabel();
        jScrollPaneRestOfCountries = new javax.swing.JScrollPane();
        jListCountries = new javax.swing.JList<>();
        jButtonShowMap = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setTitle("Χάρτης χωρών με δεδομένα covid19");
        setMaximumSize(new java.awt.Dimension(510, 344));
        setMinimumSize(new java.awt.Dimension(510, 344));
        setPreferredSize(new java.awt.Dimension(510, 344));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelCountrySelection.setText("Επιλογή βασικής χώρας");
        getContentPane().add(jLabelCountrySelection);
        jLabelCountrySelection.setBounds(18, 12, 230, 14);

        getContentPane().add(jComboBoxCountry);
        jComboBoxCountry.setBounds(6, 35, 250, 20);

        jLabelRestOfCountries.setText("Υπόλοιπες χώρες στον χάρτη");
        getContentPane().add(jLabelRestOfCountries);
        jLabelRestOfCountries.setBounds(15, 92, 240, 14);

        jScrollPaneRestOfCountries.setViewportView(jListCountries);

        getContentPane().add(jScrollPaneRestOfCountries);
        jScrollPaneRestOfCountries.setBounds(6, 114, 481, 170);

        jButtonShowMap.setText("Προβολή σε χάρτη");
        jButtonShowMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowMapActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowMap);
        jButtonShowMap.setBounds(290, 70, 180, 23);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/covidwallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 500, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowMapActionPerformed
        showMap();
    }//GEN-LAST:event_jButtonShowMapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonShowMap;
    private javax.swing.JComboBox<String> jComboBoxCountry;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCountrySelection;
    private javax.swing.JLabel jLabelRestOfCountries;
    private javax.swing.JList<String> jListCountries;
    private javax.swing.JScrollPane jScrollPaneRestOfCountries;
    // End of variables declaration//GEN-END:variables



    //Φορτώνουμε το combo και την λιστα με τις χώρες
    public void populateCountryComboBoxAndList() {
        //Καθαρίζουμε το combo
        if(jComboBoxCountry.getSelectedIndex()!=-1){
            jComboBoxCountry.setModel(new DefaultComboBoxModel());
        }
       //φέρνουμε τις χώρες απο την βάση
        List<Country> countries = db.GetCountriesListFromDb();
        DefaultListModel listCountriesModel = new DefaultListModel();
        //προσθέτουμε μια προς μια τις χώρες
        for(Country country : countries) {
            jComboBoxCountry.addItem(country.getName());
            listCountriesModel.addElement(country.getName());
        }
        jListCountries.setModel(listCountriesModel);
    }

    //Εμφανίζουμε τον χάρτη
    private void showMap() {
        //Δεν χρειαζόμαστε πλέον το παράθυρο επιλογής χωρών
        this.setVisible(false);
        //Η λίστα με τα ονόματα των χωρών που επιλέγει ο χρήστης
        List<String> selectedCountries = new ArrayList<String>();
        //Φορτώνουμε στην λίστα την επιλογή το combo
        selectedCountries.add(jComboBoxCountry.getSelectedItem().toString());
        //Φορτώνουμε στην λίστα τις επιλογές της jlist
        selectedCountries.addAll(jListCountries.getSelectedValuesList());
        
        if(selectedCountries.size()<=0){
            JOptionPane.showConfirmDialog(null, "Επιλέξτε πρώτα μια χώρα", "Χάρτης χώρας", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        
        List<MappingDataDb> mappingData = new ArrayList<MappingDataDb>();
        //Φτιάχνουμε απο την λίστα των ονομάτων των χωρών μια λίστα mappingdata
        for(String name : selectedCountries){
            //Πέρνουμε τα τελευταία covid data της χώρας απο την βάση
            MappingDataDb map = db.GetCountrysMapData(name);
            mappingData.add(map);
        }
        //Καλούμε το παράθυρο του χάρτη και περνάμε τα δεδομένα
        ShowMap showMap = new ShowMap();
        showMap.Display(mappingData);
    }
    
    //Το Εικονίδιο στην γωνία του παραθύρου
    private void setIconImage() {
        Image image = new ImageIcon(this.getClass().getResource("/resources/covid-19.png")).getImage();
        this.setIconImage(image);
    }
}
