package views;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Pantelis Ioannidis
 * @author Nick Dimitrakarakos
 * @author Efthimios Georgakis 
 * @author Aris Dimakakos
 */
public class FrameAbout extends javax.swing.JFrame {

    /**
     * Creates new form FrameAbout
     */
    public FrameAbout() {
        initComponents();
        setIconImage();
    }

    //Το Εικονίδιο στην γωνία του παραθύρου
    private void setIconImage() {
        Image image = new ImageIcon(this.getClass().getResource("/resources/covid-19.png")).getImage();
        this.setIconImage(image);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jLabelProjectDate = new javax.swing.JLabel();
        jLabelProductOwner = new javax.swing.JLabel();
        jLabelProgrammer1 = new javax.swing.JLabel();
        jLabelProgrammer2 = new javax.swing.JLabel();
        jLabelProgrammer3 = new javax.swing.JLabel();
        jLabelProgrammer4 = new javax.swing.JLabel();
        jLabelScrumTeam = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelBackground = new javax.swing.JLabel();

        setTitle("Σχετικά με το πρόγραμμα");
        setMaximumSize(new java.awt.Dimension(507, 380));
        setMinimumSize(new java.awt.Dimension(507, 380));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelHeader.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabelHeader.setText("Covid19 Stats");
        getContentPane().add(jLabelHeader);
        jLabelHeader.setBounds(64, 25, 390, 47);

        jLabelProjectDate.setText("ΕΑΠ ΠΛΗ24 3η εργασία 2021");
        getContentPane().add(jLabelProjectDate);
        jLabelProjectDate.setBounds(64, 90, 390, 14);

        jLabelProductOwner.setText("Καθηγητής - Σύμβουλος: Διονύσης Αδαμόπουλος");
        getContentPane().add(jLabelProductOwner);
        jLabelProductOwner.setBounds(64, 112, 400, 14);

        jLabelProgrammer1.setText("Ιωαννίδης Παντελής");
        getContentPane().add(jLabelProgrammer1);
        jLabelProgrammer1.setBounds(70, 190, 380, 14);

        jLabelProgrammer2.setText("Δημητρακαράκος Νικόλαος");
        getContentPane().add(jLabelProgrammer2);
        jLabelProgrammer2.setBounds(70, 210, 380, 14);

        jLabelProgrammer3.setText("Γεωργάκης Ευθύμιος");
        getContentPane().add(jLabelProgrammer3);
        jLabelProgrammer3.setBounds(70, 230, 380, 14);

        jLabelProgrammer4.setText("Δημακάκος Αριστείδης");
        getContentPane().add(jLabelProgrammer4);
        jLabelProgrammer4.setBounds(70, 250, 370, 14);

        jLabelScrumTeam.setText("Ομάδα Ανάπτυξης");
        getContentPane().add(jLabelScrumTeam);
        jLabelScrumTeam.setBounds(70, 160, 110, 14);

        jButtonClose.setText("Κλείσιμο");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose);
        jButtonClose.setBounds(180, 290, 130, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(70, 180, 380, 2);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/covidwallpaper.jpg"))); // NOI18N
        jLabelBackground.setToolTipText("");
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 570, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Κλείνει το παράθυρο
    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelProductOwner;
    private javax.swing.JLabel jLabelProgrammer1;
    private javax.swing.JLabel jLabelProgrammer2;
    private javax.swing.JLabel jLabelProgrammer3;
    private javax.swing.JLabel jLabelProgrammer4;
    private javax.swing.JLabel jLabelProjectDate;
    private javax.swing.JLabel jLabelScrumTeam;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}

