package views;

import controllers.APIController;
import controllers.DbOperations;
import java.awt.Image;
import models.TimeSeriesCase;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import models.CountryTimeSeries;

/**
 *
 * @author Pantelis Ioannidis
 * @author Nick Dimitrakarakos
 */

// R1 Διαχείριση δεδομένων Covid19
public class FrameDataManagement extends javax.swing.JFrame {

    APIController api;
    DbOperations dbOperations;

    /**
     * Creates new form FrameDataManagement
     */
    public FrameDataManagement() {
        initComponents();
        setIconImage();
        dbOperations = new DbOperations();
        api = new APIController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonInsertCountries = new javax.swing.JButton();
        jButtonInsertData = new javax.swing.JButton();
        jButtonDeleteCountries = new javax.swing.JButton();
        jButtonDeleteData = new javax.swing.JButton();
        jCheckBoxDeaths = new javax.swing.JCheckBox();
        jCheckBoxConfirmed = new javax.swing.JCheckBox();
        jCheckBoxRecovered = new javax.swing.JCheckBox();
        jCheckBoxLimitCountiesSelection = new javax.swing.JCheckBox();
        jLabelCategoriesLine1 = new javax.swing.JLabel();
        jLabelCategoriesLine2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextMessages = new javax.swing.JTextPane();
        jLabelBackground = new javax.swing.JLabel();

        setTitle("Διαχείριση δεδομένων Covid19");
        setMaximumSize(new java.awt.Dimension(720, 370));
        setMinimumSize(new java.awt.Dimension(720, 370));
        setPreferredSize(new java.awt.Dimension(720, 370));
        getContentPane().setLayout(null);

        jButtonInsertCountries.setText("Εισαγωγή χωρών");
        jButtonInsertCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertCountriesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsertCountries);
        jButtonInsertCountries.setBounds(60, 60, 190, 23);

        jButtonInsertData.setText("Εισαγωγή δεδομένων");
        jButtonInsertData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertDataActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsertData);
        jButtonInsertData.setBounds(60, 100, 190, 23);

        jButtonDeleteCountries.setText("Διαγραφή χωρών");
        jButtonDeleteCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCountriesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeleteCountries);
        jButtonDeleteCountries.setBounds(440, 60, 190, 23);

        jButtonDeleteData.setText("Διαγραφή δεδομένων");
        jButtonDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteDataActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeleteData);
        jButtonDeleteData.setBounds(440, 100, 190, 23);

        jCheckBoxDeaths.setSelected(true);
        jCheckBoxDeaths.setText("Θάνατοι");
        getContentPane().add(jCheckBoxDeaths);
        jCheckBoxDeaths.setBounds(190, 170, 150, 23);

        jCheckBoxConfirmed.setSelected(true);
        jCheckBoxConfirmed.setText("Κρούσματα");
        getContentPane().add(jCheckBoxConfirmed);
        jCheckBoxConfirmed.setBounds(190, 200, 150, 23);

        jCheckBoxRecovered.setSelected(true);
        jCheckBoxRecovered.setText("Αναρώσεις");
        getContentPane().add(jCheckBoxRecovered);
        jCheckBoxRecovered.setBounds(190, 230, 150, 23);

        jCheckBoxLimitCountiesSelection.setText("Επιλογή περιορισμένων χωρών");
        getContentPane().add(jCheckBoxLimitCountiesSelection);
        jCheckBoxLimitCountiesSelection.setBounds(60, 140, 280, 20);

        jLabelCategoriesLine1.setText("Κατηγορίες");
        getContentPane().add(jLabelCategoriesLine1);
        jLabelCategoriesLine1.setBounds(60, 190, 130, 14);

        jLabelCategoriesLine2.setText("προς εισαγωγή");
        getContentPane().add(jLabelCategoriesLine2);
        jLabelCategoriesLine2.setBounds(60, 210, 130, 14);

        jTextMessages.setEditable(false);
        jTextMessages.setBackground(javax.swing.UIManager.getDefaults().getColor("scrollbar"));
        jScrollPane3.setViewportView(jTextMessages);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(50, 260, 590, 50);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/covidwallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 710, 330);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Αν για λόγους ταχύτητας ο χρήστης επιλέξει περιορισμό χωρων, επιστρέφουμε μια λίστα μόνο με 3 χώρες 
    private List<CountryTimeSeries> limitCountries(List<CountryTimeSeries> ltm){
        return ltm.stream()
                .filter(x->x.country.equals("Greece") || x.country.equals("Germany") || x.country.equals("Italy"))
                .collect(Collectors.toList());
    }
    
    private void jButtonInsertCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertCountriesActionPerformed
        DisableAllButtons();
        jTextMessages.setText("ΠΑΡΑΚΑΛΩ ΠΕΡΙΜΕΝΕΤΕ.\n Εισαγωγή χωρών σε εξέλιξη.");
        //Εκτελούμε τις ενέργεις στην βάση και το API σε νήμα για να μην παγώσει το UI
        SwingWorker sw1 = new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {
                //Πάρε να confirmed δεδομένα απο το API
                List<CountryTimeSeries> ltm = api.GetTimeSeries(TimeSeriesCase.CONFIRMED);
                if(jCheckBoxLimitCountiesSelection.isSelected())
                    ltm=limitCountries(ltm);
                //Αποθήκευσε τις χώρες στην βάση
                dbOperations.AddCountriesThatAreNotInDB(ltm);
                return null;
            }

            @Override
            protected void process(List chunks) {

            }

            @Override
            protected void done() {
                EnableAllButtons();
                jTextMessages.setText("");
            }
        };

        sw1.execute();
    }//GEN-LAST:event_jButtonInsertCountriesActionPerformed

    private void jButtonInsertDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertDataActionPerformed
        DisableAllButtons();
        jTextMessages.setText("ΠΑΡΑΚΑΛΩ ΠΕΡΙΜΕΝΕΤΕ 2-7 λεπτά.\n Εισαγωγή δεδομένων covid σε εξέλιξη.");
        //Εκτελούμε τις ενέργεις στην βάση και το API σε νήμα για να μην παγώσει το UI
        SwingWorker sw1 = new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {
                if ((!jCheckBoxConfirmed.isSelected() && !jCheckBoxDeaths.isSelected() && !jCheckBoxRecovered.isSelected())) {
                    JOptionPane.showMessageDialog(null, "Δεν έχετε επιλέξει καμία κατηγορία δεδομένων");
                }
                //Αν ο χρήστης ζήτησε δεδομένα για Confirmed
                if (jCheckBoxConfirmed.isSelected()) {
                    //Πάρε να confirmed δεδομένα απο το API
                    List<CountryTimeSeries> ltm = api.GetTimeSeries(TimeSeriesCase.CONFIRMED);
                    if(jCheckBoxLimitCountiesSelection.isSelected())
                        ltm=limitCountries(ltm);
                    //Αποθήκευσε την χώρα αν δεν υπάρχει και τα δεδομένα της
                    dbOperations.AddCountriesThatAreNotInDB(ltm);
                    dbOperations.AddTimeSeriesInDatabase(ltm, TimeSeriesCase.CONFIRMED);
                }
                //Αν ο χρήστης ζήτησε δεδομένα για Deaths
                if (jCheckBoxDeaths.isSelected()) {
                    //Πάρε να deaths δεδομένα απο το API
                    List<CountryTimeSeries> ltm = api.GetTimeSeries(TimeSeriesCase.DEATHS);
                    if(jCheckBoxLimitCountiesSelection.isSelected())
                        ltm=limitCountries(ltm);
                    //Αποθήκευσε την χώρα αν δεν υπάρχει και τα δεδομένα της
                    dbOperations.AddCountriesThatAreNotInDB(ltm);
                    dbOperations.AddTimeSeriesInDatabase(ltm, TimeSeriesCase.DEATHS);
                }
                //Αν ο χρήστης ζήτησε δεδομένα για Recovered
                if (jCheckBoxRecovered.isSelected()) {
                    //Πάρε να recovered δεδομένα απο το API
                    List<CountryTimeSeries> ltm = api.GetTimeSeries(TimeSeriesCase.RECOVERED);
                    if(jCheckBoxLimitCountiesSelection.isSelected())
                        ltm=limitCountries(ltm);
                    //Αποθήκευσε την χώρα αν δεν υπάρχει και τα δεδομένα της
                    dbOperations.AddCountriesThatAreNotInDB(ltm);
                    dbOperations.AddTimeSeriesInDatabase(ltm, TimeSeriesCase.RECOVERED);
                }
                return null;
            }

            @Override
            protected void process(List chunks) {

            }

            @Override
            protected void done() {
                EnableAllButtons();
                jTextMessages.setText("");
            }
        };

        sw1.execute();
    }//GEN-LAST:event_jButtonInsertDataActionPerformed

    private void jButtonDeleteCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCountriesActionPerformed
        DisableAllButtons();
        jTextMessages.setText("ΠΑΡΑΚΑΛΩ ΠΕΡΙΜΕΝΕΤΕ.\n Διαγραφή χωρών σε εξέλιξη.");
        //Εκτελούμε τις ενέργεις στην βάση και το API σε νήμα για να μην παγώσει το UI
        SwingWorker sw1 = new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {
                //Διαγράφουμε όλες τις χώρες απο την βάση
                dbOperations.DeleteAllCountries();
                return null;
            }

            @Override
            protected void process(List chunks) {

            }

            @Override
            protected void done() {
                EnableAllButtons();
                jTextMessages.setText("");
            }
        };

        sw1.execute();
        
        
    }//GEN-LAST:event_jButtonDeleteCountriesActionPerformed

    //Διαγραφή δεδομέων covid
    private void jButtonDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteDataActionPerformed
        DisableAllButtons();
        jTextMessages.setText("ΠΑΡΑΚΑΛΩ ΠΕΡΙΜΕΝΕΤΕ.\n Διαγραφή δεδομένων covid σε εξέλιξη.");
        //Εκτελούμε τις ενέργεις στην βάση και το API σε νήμα για να μην παγώσει το UI
        SwingWorker sw1 = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                //Διαγράφουμε όλα τα covid data απο την βάση
                dbOperations.DeleteAllCovidData();
                return null;
            }

            @Override
            protected void process(List chunks) {

            }

            @Override
            protected void done() {
                EnableAllButtons();
                jTextMessages.setText("");
            }
        };

        sw1.execute();
        
        
    }//GEN-LAST:event_jButtonDeleteDataActionPerformed

    //Κάνουμε disabled τα checkbox ώστε ο χρήστης να μην μπορεί να τα αλλάξει
    public void EnableAllButtons() {
        jButtonDeleteCountries.setEnabled(true);
        jButtonDeleteData.setEnabled(true);
        jButtonInsertCountries.setEnabled(true);
        jButtonInsertData.setEnabled(true);
        jCheckBoxConfirmed.setEnabled(true);
        jCheckBoxDeaths.setEnabled(true);
        jCheckBoxRecovered.setEnabled(true);
        jCheckBoxLimitCountiesSelection.setEnabled(true);
    }

    //Κάνουμε enabled τα checkbox ώστε ο χρήστης να μπορεί να τα αλλάξει
    public void DisableAllButtons() {
        jButtonDeleteCountries.setEnabled(false);
        jButtonDeleteData.setEnabled(false);
        jButtonInsertCountries.setEnabled(false);
        jButtonInsertData.setEnabled(false);
        jCheckBoxConfirmed.setEnabled(false);
        jCheckBoxDeaths.setEnabled(false);
        jCheckBoxRecovered.setEnabled(false);
        jCheckBoxLimitCountiesSelection.setEnabled(false);
    }
    
    //Το Εικονίδιο στην γωνία του παραθύρου
    private void setIconImage() {
        Image image = new ImageIcon(this.getClass().getResource("/resources/covid-19.png")).getImage();
        this.setIconImage(image);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteCountries;
    private javax.swing.JButton jButtonDeleteData;
    private javax.swing.JButton jButtonInsertCountries;
    private javax.swing.JButton jButtonInsertData;
    private javax.swing.JCheckBox jCheckBoxConfirmed;
    private javax.swing.JCheckBox jCheckBoxDeaths;
    private javax.swing.JCheckBox jCheckBoxLimitCountiesSelection;
    private javax.swing.JCheckBox jCheckBoxRecovered;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCategoriesLine1;
    private javax.swing.JLabel jLabelCategoriesLine2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextMessages;
    // End of variables declaration//GEN-END:variables
}
