package views;

import helpers.DatabaseUtils;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Pantelis Ioannidis
 * @author Nick Dimitrakarakos
 * @author Efthimios Georgakis 
 * @author Aris Dimakakos
 */

// R1 Κεντική οθόνη επιλογών
public class MainFrame extends javax.swing.JFrame {
    FrameDataManagement frameDataManagement = new FrameDataManagement();
    FrameDataDisplay frameDataDisplay = new FrameDataDisplay();
    FrameMapSelection frameMapSelection = new FrameMapSelection();
    FrameAbout frameAbout = new FrameAbout();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        initComponents();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jButtonDataManagement = new javax.swing.JButton();
        jButtonDataDisplay = new javax.swing.JButton();
        jButtonMap = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBarMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();
        mnuFrames = new javax.swing.JMenu();
        mnuDataManagement = new javax.swing.JMenuItem();
        mnuDataDisplay = new javax.swing.JMenuItem();
        mnuMap = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Σύστημα Covid19-Stats");
        setMaximumSize(new java.awt.Dimension(800, 460));
        setMinimumSize(new java.awt.Dimension(800, 460));
        setPreferredSize(new java.awt.Dimension(800, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 460));
        getContentPane().setLayout(null);

        jLabelHeader.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("Covid19 Stats");
        jLabelHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelHeader);
        jLabelHeader.setBounds(210, 40, 320, 60);

        jButtonDataManagement.setText("Διαχείριση δεδομένων Covid19");
        jButtonDataManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataManagementActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDataManagement);
        jButtonDataManagement.setBounds(250, 140, 240, 25);

        jButtonDataDisplay.setText("Προβολή δεδομένων Covid19 ανά χώρα");
        jButtonDataDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDataDisplay);
        jButtonDataDisplay.setBounds(220, 200, 300, 25);

        jButtonMap.setText("Προβολή δεδομένων Covid19 σε χάρτη");
        jButtonMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMapActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMap);
        jButtonMap.setBounds(220, 260, 300, 25);

        jButtonExit.setText("Έξοδος");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(300, 320, 150, 25);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/covidwallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 800, 430);

        mnuFile.setText("Αρχείο");

        mnuExit.setText("Έξοδος");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        jMenuBarMain.add(mnuFile);

        mnuFrames.setText("Εργασίες");

        mnuDataManagement.setText("Διαχείριση δεδομένων Covid19");
        mnuDataManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDataManagementActionPerformed(evt);
            }
        });
        mnuFrames.add(mnuDataManagement);

        mnuDataDisplay.setText("Προβολή δεδομένων Covid19 ανά χώρα");
        mnuDataDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDataDisplayActionPerformed(evt);
            }
        });
        mnuFrames.add(mnuDataDisplay);

        mnuMap.setText("Προβολή δεδομένων Covid19 σε χάρτη");
        mnuMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMapActionPerformed(evt);
            }
        });
        mnuFrames.add(mnuMap);

        jMenuBarMain.add(mnuFrames);

        mnuHelp.setText("Πληροφορίες");

        mnuAbout.setText("Σχετικά");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuAbout);

        jMenuBarMain.add(mnuHelp);

        setJMenuBar(jMenuBarMain);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        exitApp();
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuDataManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDataManagementActionPerformed
        showDataManagement();
    }//GEN-LAST:event_mnuDataManagementActionPerformed

    private void mnuDataDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDataDisplayActionPerformed

        showDataDisplay();
    }//GEN-LAST:event_mnuDataDisplayActionPerformed

    private void mnuMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMapActionPerformed
        showMap();
    }//GEN-LAST:event_mnuMapActionPerformed

    private void jButtonDataManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataManagementActionPerformed
        showDataManagement();
    }//GEN-LAST:event_jButtonDataManagementActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        exitApp();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonDataDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataDisplayActionPerformed
        showDataDisplay();
    }//GEN-LAST:event_jButtonDataDisplayActionPerformed

    private void jButtonMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMapActionPerformed
        showMap();
    }//GEN-LAST:event_jButtonMapActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        showAboutWindow();
    }//GEN-LAST:event_mnuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void setLookAndFeel() {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDataDisplay;
    private javax.swing.JButton jButtonDataManagement;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonMap;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenuItem mnuDataDisplay;
    private javax.swing.JMenuItem mnuDataManagement;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuFrames;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuMap;
    // End of variables declaration//GEN-END:variables

    private void showDataDisplay() {
        if(frameDataDisplay==null){
            frameDataDisplay = new FrameDataDisplay();
        }
        frameDataDisplay.populateComponents();
        frameDataDisplay.setVisible(true);
    }

    private void showMap() {
        if (frameMapSelection == null){
            frameMapSelection = new FrameMapSelection();
        }
        frameMapSelection.populateCountryComboBoxAndList();
        frameMapSelection.setVisible(true);
    }

    private void showDataManagement() {
        if (frameDataManagement == null){
            frameDataManagement = new FrameDataManagement();
        }
        frameDataManagement.setVisible(true);
    }

    private void exitApp() {
        System.exit(0);
    }

    private void showAboutWindow() {
        if (frameAbout == null){
            frameAbout = new FrameAbout();
        }
        frameAbout.setVisible(true);
    }

    //Το Εικονίδιο στην γωνία του παραθύρου
    private void setIconImage() {
        Image image = new ImageIcon(this.getClass().getResource("/resources/covid-19.png")).getImage();
        this.setIconImage(image);
    }
}
